name: ca_flutter_slide

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # ルーティング
  auto_route: ^7.8.3

  # アノテーション
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  
  # hooks
  flutter_hooks: ^0.18.6

  # riverpod
  hooks_riverpod: ^2.3.6

  # For DateTime
  intl: ^0.18.0

  # Gap
  gap: ^3.0.1

  flutter_deck: ^0.11.1

  rive: ^0.12.4

  auto_size_text: ^3.0.0

dev_dependencies:
  # For Test
  flutter_test:
    sdk: flutter
  flutter_hooks_test: ^0.0.4
  mocktail: ^0.3.0

  # 自動生成
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.4.0
  
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3

  # Linter
  very_good_analysis: ^5.0.0+1

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true
    rive: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/
