name: ca_flutter_slide

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # アノテーション
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  
  # hooks
  flutter_hooks: ^0.21.0

  # riverpod
  hooks_riverpod: ^2.5.1

  # For DateTime
  intl: ^0.18.1

  # Gap
  gap: ^3.0.1

  flutter_deck: ^0.13.0

  rive: ^0.13.1

  auto_size_text: ^3.0.0

  universal_html: ^2.2.4

  flutter_svg: ^2.0.10+1

  syntax_highlight: ^0.4.0

dependency_overrides:
  web: ^0.4.0

dev_dependencies:
  # For Test
  flutter_test:
    sdk: flutter
  flutter_hooks_test: ^0.0.5
  mocktail: ^1.0.3

  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

  # Linter
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true
    rive: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
